name: "Step - Deploy"

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      artifact_name:
        required: true
        type: string
      resource_group_name:
        required: true
        type: string
      app_service_name:
        required: true
        type: string
      app_service_slot_name:
        required: true
        type: string
    secrets:
      azure_client_id:
        required: true
        description: "Client ID for Azure Service Principal"
      azure_subscription_id:
        required: true
        description: "Azure Subscription ID for the targeted Resource Group"
      azure_tenant_id:
        required: true
        description: "Azure Tenant ID for the targeted Resource Group"

jobs:
  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest

    concurrency:
      group: deploy-to-azure
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.azure_client_id }}
          tenant-id: ${{ secrets.azure_tenant_id }}
          subscription-id: ${{ secrets.azure_subscription_id }}

      - name: Run Bicep
        run: |
          az deployment group create \
            --name ${{ inputs.env }}-deployment-${{ github.run_number }} \
            --template-file infrastructure/main.bicep \
            --parameters infrastructure/environments/${{ inputs.env }}.bicepparam \
            --resource-group ${{ inputs.resource_group_name }} \
            --verbose

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact_name }}
          path: publish

      - name: Get publish profile
        id: publishprofile
        run: |
          profile=$(az webapp deployment list-publishing-profiles --resource-group ${{ inputs.resource_group_name }} --name ${{ inputs.app_service_name }} --slot ${{ inputs.app_service_slot_name }} --xml)
          echo "PUBLISH_PROFILE=$profile" >> $GITHUB_OUTPUT

      - name: Deploy to Slot
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ inputs.app_service_name }}
          slot-name: ${{ inputs.app_service_slot_name }}
          publish-profile: ${{ steps.publishprofile.outputs.PUBLISH_PROFILE }}
          package: publish/

      - name: Swap slots
        run: |
          az webapp deployment slot swap -g ${{ inputs.resource_group_name }} -n ${{ inputs.app_service_name }} --slot ${{ inputs.app_service_slot_name }} --target-slot production --verbose
